import { execFile } from 'node:child_process';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { isIP } from 'node:net';
import path from 'node:path';
import { promisify } from 'node:util';
import type { PanelState, PeerView, RuntimeConfig } from '../shared/types.js';
import { networkCidr } from './network.js';
import { protocolLines } from './protocol.js';

const execFileAsync = promisify(execFile);

function endpoint(host: string, port: number): string {
  const normalized = isIP(host) === 6 && !host.startsWith('[') ? `[${host}]` : host;
  return `${normalized}:${port}`;
}

function firewallCommands(state: PanelState, runtime: RuntimeConfig): { up: string; down: string } {
  const subnet = networkCidr(state.interface.address);
  const parts = [
    `iptables -A FORWARD -i %i -j ACCEPT`,
    `iptables -A FORWARD -o %i -j ACCEPT`,
    `iptables -t nat -A POSTROUTING -s ${subnet} -o ${runtime.outboundDevice} -j MASQUERADE`,
  ];
  const down = [
    `iptables -D FORWARD -i %i -j ACCEPT`,
    `iptables -D FORWARD -o %i -j ACCEPT`,
    `iptables -t nat -D POSTROUTING -s ${subnet} -o ${runtime.outboundDevice} -j MASQUERADE`,
  ];
  return { up: parts.join('; '), down: down.join('; ') };
}

export function renderServerConfig(state: PanelState, runtime: RuntimeConfig): string {
  const firewall = firewallCommands(state, runtime);
  const lines = [
    `# Generated by AWG Panel — protocol ${state.protocol.version}`,
    '[Interface]',
    `PrivateKey = ${state.server.privateKey}`,
    `Address = ${state.interface.address}`,
    `ListenPort = ${runtime.listenPort}`,
    `MTU = ${state.interface.mtu}`,
    ...protocolLines(state.protocol),
    `PostUp = ${firewall.up}`,
    `PostDown = ${firewall.down}`,
  ];

  for (const peer of state.peers.filter((item) => item.enabled)) {
    lines.push(
      '',
      `# ${peer.name} (${peer.id})`,
      '[Peer]',
      `PublicKey = ${peer.publicKey}`,
      `PresharedKey = ${peer.presharedKey}`,
      `AllowedIPs = ${peer.address}/32`,
    );
  }
  return `${lines.join('\n')}\n`;
}

export function renderClientConfig(state: PanelState, runtime: RuntimeConfig, peerId: string): string {
  const peer = state.peers.find((item) => item.id === peerId);
  if (!peer) throw new Error('Конфигурация не найдена');

  const lines = [
    `# ${peer.name} — AWG ${state.protocol.version}`,
    '[Interface]',
    `PrivateKey = ${peer.privateKey}`,
    `Address = ${peer.address}/32`,
  ];
  if (state.interface.dns.length) lines.push(`DNS = ${state.interface.dns.join(', ')}`);
  lines.push(`MTU = ${state.interface.mtu}`, ...protocolLines(state.protocol), '', '[Peer]');
  lines.push(
    `PublicKey = ${state.server.publicKey}`,
    `PresharedKey = ${peer.presharedKey}`,
    `Endpoint = ${endpoint(runtime.endpointHost, runtime.listenPort)}`,
    `AllowedIPs = ${state.interface.allowedIps.join(', ')}`,
  );
  if (state.interface.persistentKeepalive > 0) {
    lines.push(`PersistentKeepalive = ${state.interface.persistentKeepalive}`);
  }
  return `${lines.join('\n')}\n`;
}

interface LivePeer {
  endpoint: string | null;
  latestHandshakeAt: string | null;
  online: boolean;
  receivedBytes: number;
  sentBytes: number;
}

function parseDump(stdout: string): Map<string, LivePeer> {
  const result = new Map<string, LivePeer>();
  const lines = stdout.trim().split('\n').slice(1);
  const now = Math.floor(Date.now() / 1000);
  for (const line of lines) {
    const columns = line.split('\t');
    if (columns.length < 8) continue;
    const handshake = Number(columns[4]);
    result.set(columns[0], {
      endpoint: columns[2] && columns[2] !== '(none)' ? columns[2] : null,
      latestHandshakeAt: handshake > 0 ? new Date(handshake * 1000).toISOString() : null,
      online: handshake > 0 && now - handshake < 180,
      receivedBytes: Number(columns[5]) || 0,
      sentBytes: Number(columns[6]) || 0,
    });
  }
  return result;
}

export class AwgManager {
  readonly configPath: string;
  private applyQueue: Promise<unknown> = Promise.resolve();

  constructor(private readonly runtime: RuntimeConfig) {
    this.configPath = path.join(runtime.dataDir, `${runtime.interfaceName}.conf`);
  }

  async apply(state: PanelState): Promise<void> {
    const run = () => this.applyNow(state);
    const result = this.applyQueue.then(run, run);
    this.applyQueue = result.then(() => undefined, () => undefined);
    return result;
  }

  private async applyNow(state: PanelState): Promise<void> {
    await mkdir(this.runtime.dataDir, { recursive: true, mode: 0o700 });
    if (!this.runtime.dryRun) {
      try {
        await readFile(this.configPath);
        await execFileAsync('awg-quick', ['down', this.configPath]);
      } catch {
        // The interface may not exist on first start; the following up is authoritative.
      }
    }

    await writeFile(this.configPath, renderServerConfig(state, this.runtime), { mode: 0o600 });
    await chmod(this.configPath, 0o600);
    if (!this.runtime.dryRun) await execFileAsync('awg-quick', ['up', this.configPath]);
  }

  async peerViews(state: PanelState): Promise<{ status: 'up' | 'down' | 'unknown'; peers: PeerView[] }> {
    let live = new Map<string, LivePeer>();
    let status: 'up' | 'down' | 'unknown' = this.runtime.dryRun ? 'unknown' : 'down';
    if (!this.runtime.dryRun) {
      try {
        const { stdout } = await execFileAsync('awg', ['show', this.runtime.interfaceName, 'dump']);
        live = parseDump(stdout);
        status = 'up';
      } catch {
        status = 'down';
      }
    }

    return {
      status,
      peers: state.peers.map((peer) => {
        const current = live.get(peer.publicKey);
        return {
          id: peer.id,
          name: peer.name,
          address: peer.address,
          enabled: peer.enabled,
          createdAt: peer.createdAt,
          online: Boolean(current?.online),
          latestHandshakeAt: current?.latestHandshakeAt ?? null,
          endpoint: current?.endpoint ?? null,
          receivedBytes: current?.receivedBytes ?? 0,
          sentBytes: current?.sentBytes ?? 0,
        };
      }),
    };
  }
}
